### ISSUE TITLE
Overview and roadmap

### ISSUE THREAD

**Issue by ghost** [elastic/elastic-stack-installers#1]
Meeting notes below. Notes: beats cross-compiles windows binaries in docker, this will not work for installer.

Short-term goal: have beats installers run the same way windows CI environment currently packages installers.

Long-term goal: add windows box to beats packaging pipeline to build and package windows binaries and installers.

https://docs.google.com/document/d/1zKUwsZU77xjf1hI9L_z-UgbzvxbeCAhIVuwqk2gm5b0/

### Repository
- [ ] Integrate per-beat installer into elastic/beats

### Packaging
- [ ] Beat per MSI
- [ ] All beats in single MSI (maybe)
- [ ] Establish service dependencies (TCP/IP, etc)

### Artifacts
- [ ] short-term: grab built .zip and build package from that
- [ ] long-term: build beats windows binaries and MSI under windows, integrated into general beats pipeline

### Bitness
- [ ] Provide x86 version. Do we still care about x86/32bit variants?
- [ ] Provide x64 version.

### UI - Provide per-beat configuration UI to:
- [ ] allow the beat to be installed as a service.
- [ ] allow the beat to connect to downstream component.
- [ ] run Kibana dashboard setup
- [ ] configure/enable available modules
- [ ] Direct user to the guide page for the beat to continue/modify/extend configuration.

### CM / Fleet integration
- [ ] ...

### Testing / CI
- [ ] ...

UPD: restored original text of the issue
