### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by ghost** [elastic/elastic-stack-installers#20]
Table of Contents for test-related isues
- [ ] Build runner unit tests <issue # HERE>
- [ ] Package compiler unit tests  <issue # HERE>
- [ ] Build configuration persistence unit tests <issue # HERE>
