### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by ygel** [elastic/elastic-stack-installers#3]
### TODOs
- [x] Build any beat from cli using packages from artifacts-api.
- [x] Add beat-specific icon to show up in Add/Remove Programs and MSI.
- [x] Support for x86 and x64 msi build workflows.
- [x] Fix quiet install failure (`/q`, `/qn`, `/q+`).
- [x] Fix administrative install failure (`/a`).
- [x] Add support for `all` build target - builds all known installers. 4cbc102
- [x] ~~Grab short description of a beat from its `README.md` file.~~ Dependency removed in 92fa202.
- [x] ~Cache used ProductId (guid) -> version map in `config.yaml`.~ Deferred.
- [x] Evaluate switching to "SDK-style" project format for XXXCompiler projects.
- [x] Create meta-ticket for installer test proces. Connect with Beats team and discuss testing and CI engagement. See [Installer Wiki](https://github.com/elastic/elastic-stack-installers/wiki)
- [x] Evaluate using `elastic/elasticsearch-net-abstractions` to talk to artifacts-api. #59
- [x] ~~Add support for `latest`, signifying latest version of the artifact (container).
Might not be trivial: https://github.com/elastic/infra/issues/14645, https://github.com/elastic/infra/issues/5193, https://github.com/elastic/elasticsearch-docker/issues/215#issuecomment-456816727~~ No action
- [x] Figure out when to remove the hard-link so that package can be removed from disk. d5181997. No Action: existing cleanup behavior removes links.
- [x] Convert TODO entries to Github issues.

### Converted to tickets:
- [x] Implement CLI shim for beats (and ES/Kibana later) to run from any directory using same configuration file as service. #10
- [x] Implement package signing. Add env var support for package signing. #14
- [x] After install (UI sequence) provide means to open/edit config file. #40
- [x] ~~Notify Beats team that installer build process depends on beat's `README.md` file contents, specifically line 3, containing beat description. Discuss alternatives to make it less brittle.~~ `README.md` dependency removed in 92fa202, others remain, see #4.
- [x] Configure assembly versions properly for build runner and per-package compilers. #9
- [x] Evaluate possibility of specifying external, pre-written beat-specific .yaml config (filebeat, winlogbeat, etc) file to be picked up by Beats installers. It can be on file system or pulled from GIthub for example. #11
- [x] Evaluate WixSharp's ManagedProject approach as potential v2. It provides much improved UI .customization options, custom action handling then then some. #12
- [x] Evaluate possibility of migrating existing configuration on upgrade. On install over an existing same version or upgrade ask to install fresh configuration or preserve existing. On uninstall, ask to remove data and configuration (default to `No`). #13
- [x] Evaluate possibility of using beat-specific MSI window backgrounds and other graphics assets. #15
- [x] Evaluate replacing `SimpleExec` with runner capable of returning exit codes and `stdout`/`stderr` (possibly `nullean/proc`). #16

### References
- https://github.com/elastic/beats/issues/163
- https://github.com/elastic/enhancements/issues/7001

**Comment by ygel** [comment]
Everything is accounted for in tickets and comments
