### ISSUE TITLE
Beats installer MVP

### ISSUE THREAD

**Issue by ghost** [elastic/elastic-stack-installers#32]
- [x] Release manager integration #22
- [x] Signing mechanism #14
- [x] CLI shim, #10 
- [x] Remove `functionbeat`, #33 
- [x] Remove version from path to data directories #39
- [x] Rename configuration file {beatname}.yml to {beatname}.example.yml to prevent upgrade from deleting the former. #39 
- [x] Give user further steps to follow after install finished. E.g: URL to getting started, point to .yaml config file, etc. #40

Optional:
- [ ] Talk to InfoSec wrt reuse of existing certificates
- [ ] Update Getting Started document to account for new MSI-based workflow.
