### ISSUE TITLE
Installer dependencies on metadata in Beats repository

### ISSUE THREAD

**Issue by ghost** [elastic/elastic-stack-installers#4]
Beats installer compiler has dependencies on contents of some artifacts in the Beats repository. This metadata describes each beat and is used in the Installer UI and build process to avoid hard-coded or manual input prone to be out of sync.

- [x] ~~Contents of `README.md` file, specifically `line 3`, containing one-liner beat description.~~ (dependency removed in 92fa202ab)
- [x] Contents of `LICENSE.txt` file it its entirety. This file is temporarily massaged into `.rtf` format installer expects.
- [x] Directory names (`kibana`, `module`, `modules.d`, `monitors.d`) are tagged in `config.yaml` in this repository as "mutable" and installed into a location with write/modify access by non-elevated users.

Purpose of this notification is to see how Beats team feels about current implementation and solicit feedback. See [config.yaml](https://github.com/elastic/stack-elastic-installers/blob/master/src/config/config.yaml) for more sample.

@urso @philkra @sophiec20 @Mpdreamz @russcam
